def get_magoosh_word_list():
    return {
        "a": ["aberrant", "aberration", "abjure", "aboveboard", "abrogate", "abstain",
              "abstruse", "abysmal", "access", "accolade", "acerbic", "acme",
              "acrimony", "adamant", "adequate", "adjudicate", "admonish", "admonitory",
              "advocate", "aesthete", "aesthetic", "affable", "affluent", "afford",
              "alacrity", "altruism", "amalgam", "ambiguous", "ambivalent",
              "ameliorate", "amenable", "amiable", "amok", "amorphous", "amply",
              "anachronism", "analogous", "anathema", "anemic", "animosity", "anodyne",
              "anomalous", "anomaly", "antedate", "antic", "antipathy", "antiquated",
              "antithetical", "apathetic", "apathy", "apex", "aphorism", "aphoristic",
              "aplomb", "apocryphal", "apogee", "apostate", "apothegm", "apotheosis",
              "appease", "appreciable", "apprehension", "approbatory", "appropriate",
              "appurtenant", "arbitrary", "arcane", "arch", "archaic", "arduous",
              "arrant", "arriviste", "arrogate", "artful", "artifice", "artless",
              "artlessness", "ascendancy", "ascetic", "ascribe", "askance", "asperity",
              "assail", "assiduously", "assuage", "atavism", "attenuate", "audacious",
              "audacity", "augment", "auspicious", "austere", "autocratic",
              "autonomously", "avarice", "avaricious", "avert", "avid"],
        "b": ["badger", "baleful", "balk", "banal", "banality", "banish", "base",
              "bastardization", "beatific", "becoming", "beg", "begrudge", "behooves",
              "belie", "belittle", "bellicose", "belligerent", "bemoan", "benighted",
              "benign", "bereft", "besiege", "besmirch", "besotted", "betray",
              "bilious", "blatant", "bleak", "blinkered", "bolster", "boon", "boorish",
              "bowdlerize", "brazen", "bridle", "bristle", "broadside", "bromide",
              "brook", "browbeat", "brusquely", "buck", "bucolic", "bumbling",
              "burgeon", "buttress", "byzantine"],
        "c": ["cadaverous", "callow", "calumny", "canard", "candid", "candidness",
              "capacity", "capitulate", "capricious", "cardinal", "carping",
              "castigate", "cataclysm", "catalyst", "catholic", "cavalier", "cede",
              "celerity", "censor", "censor", "censure", "cerebral", "chagrin",
              "champion", "charlatan", "chary", "chastise", "chastise", "chauvinism",
              "chauvinist", "check", "checkered", "chimera", "chivalrous", "choleric",
              "chortle", "churlish", "circumscribe", "circumvent", "clemency",
              "coalesce", "cogent", "cohesive", "collusion", "colossal", "commendable",
              "commensurate", "complacent", "complaisant", "complementary", "complicit",
              "compound", "concede", "conciliate", "concomitant", "conducive",
              "conflagration", "conflate", "confound", "conniving", "conniving",
              "consecrate", "conspicuous", "constituent", "constraint", "construe",
              "consummate", "contemptuous", "contentious", "contingent", "contrite",
              "contrition", "contrive", "conundrum", "convivial", "convoluted",
              "copious", "cornucopia", "corollary", "corroborate", "cosmopolitan",
              "cosseted", "coterminous", "countermand", "cow", "craven", "credence",
              "creditable", "credulity", "crestfallen", "cryptic", "crystallize",
              "culminate", "culpability", "cumbersome", "cupidity", "curmudgeon"],
        "d": ["dearth", "debase", "debonair", "debunk", "decimation", "decorous",
              "decorum", "decry", "deferential", "defray", "degrade", "deign",
              "delegate", "deleterious", "deliberate", "delineate", "demean",
              "demonstrative", "demur", "demure", "denigrate", "denote", "denouement",
              "derelict", "deride", "derisive", "derivative", "derive", "derogative",
              "desecrate", "desiccated", "desideratum", "despite", "despot",
              "destitute", "deter", "detrimental", "devolve", "diabolical", "diatribe",
              "dictatorial", "didactic", "differentiate", "diffident", "dilapidated",
              "dilatory", "dilettante", "diligent", "diminutive", "disabuse",
              "disaffected", "discord", "discreet", "discrete", "discriminate",
              "discursive", "disenfranchise", "disheartened", "disingenuous",
              "disinterested", "disparate", "dispassionate", "dispatch", "dispensation",
              "dissemble", "disseminate", "dissipate", "dissolution", "docile", "dog",
              "dogmatic", "doleful", "dolorous", "doughty", "dovetail", "dupe",
              "duplicity", "duress"],
        "e": ["ebullient", "eccentric", "eclectic", "economical", "edifying",
              "effervescent", "efficacious", "effrontery", "egotist", "egregious",
              "eke", "elaborate", "elegiac", "elicit", "elicit", "elucidate", "elude",
              "elusive", "embellish", "embroiled", "eminent", "empathetic",
              "empiricism", "emulate", "enamor", "encumber", "endemic", "enervate",
              "engender", "enjoin", "enmity", "enormity", "enthrall", "entice",
              "entrenched", "enumerate", "ephemeral", "epigram", "epiphany", "eponym",
              "equitable", "equivocal", "equivocate", "eradicate", "err", "errant",
              "erratic", "ersatz", "erudite", "eschew", "esoteric", "espouse",
              "estimable", "ethereal", "euphoria", "evanescent", "evasive",
              "evenhanded", "exacerbate", "exacting", "exalt", "exasperate",
              "excoriate", "excruciating", "execrate", "exegesis", "exemplar",
              "exemplify", "exhort", "exiguity", "exorbitant", "expansive", "expound",
              "expound", "expunge", "expurgate", "extant", "extenuating",
              "extrapolate"],
        "f": ["facetious", "facile", "factious", "factitious", "fallacious",
              "fastidious", "fawn", "feckless", "fecund", "fell", "ferret", "fete",
              "fickle", "finagle", "firebrand", "flag", "fledgling", "fleece",
              "flippant", "flounder", "flummox", "flush", "flux", "foible", "foment",
              "foolhardy", "forlorn", "forthcoming", "forthright", "fortuitous",
              "fractious", "frivolous", "frugal", "frustrate", "furtive", "futile"],
        "g": ["gaffe", "gainsay", "gall", "galvanize", "gambit", "garrulous", "gauche",
              "genial", "genteel", "germane", "gerrymander", "glean", "glib", "glut",
              "goad", "gossamer", "graft", "grandiloquent", "gregarious", "grovel",
              "guffaw", "guileless", "gumption"],
        "h": ["hackneyed", "hagiographic", "hail", "halcyon", "hamper", "hamstrung",
              "hamstrung", "haphazard", "harangue", "harried", "haughty", "hauteur",
              "hector", "hedge", "hegemony", "heretic", "heyday", "histrionic", "hoary",
              "hobble", "hodgepodge", "hoodwink", "hound", "hubris", "humdrum"],
        "i": ["iconoclast", "iconoclastic", "idiosyncrasy", "ignoble", "ignominious",
              "illicit", "illustrious", "imbibe", "imbroglio", "immaterial", "immure",
              "immutable", "impartial", "impeccable", "impecunious", "impede",
              "impending", "imperious", "impermeable", "impertinent", "impervious",
              "impetuous", "implacable", "implausible", "implicate", "implicate",
              "imponderable", "importuned", "impregnable", "improvident", "imprudent",
              "impudent", "impugn", "impute", "inadvertent", "inanity", "inarticulate",
              "incense", "incessant", "inchoate", "incisive", "inclement",
              "incongruous", "incontrovertible", "incorrigible", "incumbent",
              "indecorous", "indict", "indifference", "indigenous", "indigent",
              "indignant", "industrious", "ineffable", "ineluctable", "inequity",
              "inexorable", "infelicitous", "inflammatory", "ingenuity", "ingenuous",
              "inimical", "inimitable", "inkling", "innocuous", "inscrutable",
              "insidious", "insipid", "insolent", "insolvent", "insouciance",
              "insufferable", "intermittent", "internecine", "intimate", "intimation",
              "intransigent", "intrepid", "inundate", "inure", "invective",
              "inveterate", "invidious", "inviolable", "inviolate", "involved",
              "irascible", "irk", "irrefutable", "irresolute", "irrevocable",
              "itinerant"],
        "j": ["jargon", "jaundice", "jejune", "jingoism", "jingoist", "jocular",
              "jocular", "jovial", "jubilant", "juggernaut", "junta", "juxtapose"],
        "k": ["kowtow"],
        "l": ["label", "laborious", "lacerate", "lachrymose", "laconic", "lambast",
              "lampoon", "languid", "languish", "largess", "lascivious", "laudable",
              "leery", "lethargic", "limpid", "lionize", "litany", "loath", "lucid",
              "lugubrious"],
        "m": ["macabre", "machinate", "magisterial", "magnanimous", "maintain",
              "maladroit", "malady", "malapropism", "malevolent", "malfeasance",
              "malingerer", "malleable", "malodorous", "martial", "martinet", "maudlin",
              "maunder", "maverick", "mawkish", "maxim", "meander", "melancholy",
              "melee", "mellifluous", "mendacity", "mendicant", "mercurial",
              "mesmerize", "meteoric", "meticulous", "mettlesome", "mettlesome",
              "misanthrope", "misattribute", "misconstrue", "miscreant", "miser",
              "misogynist", "mitigate", "modicum", "mollify", "moment", "moot",
              "mordant", "moribund", "morose", "morph", "mulct", "mundane",
              "munificent", "muted", "myopic", "myriad"],
        "n": ["nadir", "negligible", "nettlesome", "noisome", "nonchalant",
              "nonplussed", "nuance", "nuance"],
        "o": ["obdurate", "objurgate", "obliging", "oblique", "obscure", "obsequious",
              "obstinate", "obstreperous", "obtain", "obtuse", "officious", "opaque",
              "opulence", "ornate", "ossify", "ostentatious", "ostracize",
              "overweening"],
        "p": ["palatable", "palaver", "palimpsest", "panacea", "panache", "panegyric",
              "paradoxical", "paragon", "pariah", "parochial", "parsimonious",
              "parvenu", "pastoral", "patent", "patronize", "paucity", "pecuniary",
              "pedantic", "pedestrian", "peevish", "pejorative", "pellucid",
              "penurious", "perceive", "percipient", "peremptory", "perennial",
              "perfidy", "perfunctory", "peripatetic", "pernicious", "perpetuate",
              "perquisite", "perspicacious", "pertinent", "perturb", "peruse",
              "petulant", "phantasmagorical", "philistine", "phlegmatic", "picayune",
              "pillory", "pine", "pinnacle", "piquant", "pith", "pithy", "pittance",
              "placate", "placid", "platitude", "plodding", "ploy", "plucky",
              "poignant", "polemic", "Pollyannaish", "ponderous", "pontificate",
              "portentous", "posit", "powwow", "pragmatic", "precarious", "precedent",
              "precipitate", "precipitous", "preclude", "precocious", "predilection",
              "preempt", "preemptive", "prescience", "presentiment", "presumption",
              "presumptuous", "prevail", "prevaricate", "primacy", "pristine",
              "probity", "prodigal", "prodigious", "profligate", "profuse", "profusion",
              "prognostication", "prolific", "prolixity", "promulgate", "propitiate",
              "propitious", "proponent", "prosaic", "proscribe", "proselytize",
              "protean", "provident", "provincial", "provisional", "puerile",
              "pugnacious", "puissant", "punctilious", "pundit", "pyrrhic"],
        "q": ["quail", "qualify", "qualm", "quandary", "querulous", "quip", "quisling",
              "quixotic", "quotidian"],
        "r": ["raconteur", "raffish", "raft", "raillery", "rakish", "rankle",
              "rapprochement", "rarefied", "rash", "ravenous", "rebuke",
              "recapitulation", "reconcile", "recondite", "recrimination", "recrudesce",
              "redoubtable", "redress", "refractory", "refute", "register", "relegate",
              "relevant", "remiss", "remonstrate", "renege", "replete", "replete",
              "reprisal", "reproach", "reprobate", "repudiate", "rescind",
              "reservation", "resignation", "resolve", "resource", "respite", "restive",
              "resurgent", "reticent", "retiring", "retract", "reverent", "ribald",
              "rile", "robust", "row", "rudimentary", "rustic"],
        "s": ["sagacious", "sanctimonious", "sanction", "sangfroid", "sanguine",
              "sardonic", "sartorial", "saturnine", "savvy", "schadenfreude",
              "scintillating", "screed", "scrupulous", "sedulous", "self-effacing",
              "semblance", "sententious", "sentimental", "serendipity", "serene",
              "simulacrum", "sinecure", "slapdash", "smattering", "smug", "snide",
              "snub", "solecism", "solicitous", "solicitude", "soporific", "sordid",
              "spartan", "specious", "spendthrift", "splenetic", "sporadic", "spurious",
              "spurn", "squander", "squelch", "staid", "stalwart", "start", "staunch",
              "steadfast", "stem", "stipend", "stolid", "stringent", "stultify",
              "stymie", "subsume", "subterfuge", "subversive", "sullen", "summit",
              "supercilious", "superfluous", "supplant", "surfeit", "surly",
              "surreptitious", "sybarite", "sycophant"],
        "t": ["taciturn", "tact", "tantamount", "tarnish", "tawdry", "taxing",
              "telling", "telltale", "temerity", "temperance", "tempered",
              "tempestuous", "tenacious", "tenacious", "tendentious", "tender",
              "thoroughgoing", "thrifty", "thwart", "timorous", "tirade", "torpor",
              "tortuous", "tout", "tractable", "transient", "transitory", "transmute",
              "travail", "travesty", "treacherous", "trenchant", "tribulation", "trite",
              "truculence", "truculent", "truncate", "tumult", "turgid", "turpitude",
              "tyro"],
        "u": ["umbrage", "unassailable", "uncanny", "uncompromising", "unconscionable",
              "undermine", "underscore", "underwrite", "unequivocal", "unflappable",
              "unforthcoming", "unimpeachable", "unnerve", "unprecedented",
              "unprepossessing", "unpropitious", "unruly", "unscrupulous", "unseemly",
              "unstinting", "untenable", "untoward", "untrammeled", "unviable",
              "upbraid", "urbane"],
        "v": ["vacillate", "vacuous", "vanquish", "variance", "vaunted", "vehement",
              "venality", "veneer", "venerate", "venial", "veracious", "verisimilitude",
              "veritable", "vicarious", "vicissitude", "vie", "vilify", "vindicate",
              "vindictive", "virago", "vitriol", "vitriolic", "vituperate",
              "vociferous", "volubility", "voracious"],
        "w": ["wanting", "wanton", "wax", "whimsical", "winsome"],
        "x": [],
        "y": [],
        "z": ["zeitgeist", "zenith"]
    }
